### ISSUE TITLE
The script breaks if the shard key is using UUID type

### ISSUE THREAD

**Issue by dryabtse** [kaloianm/workscripts#83]
In my tests the script is unable to work correctly if the shard key is using UUID:
```
2022-03-10 13:24:09,213 [INFO] Bounds: [{'location': 'US', 'xdr_device_id': UUID('00000100-95b4-4058-ba9e-c32e0fab201f')}, {'location': 'US', 'xdr_device_id': UUID('52df6ff6-cbea-4425-83f9-942e055022a4')}]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 61739/61739 [00:00<00:00, 182577.57 chunk/s]
Traceback (most recent call last):
  File "defragment_sharded_collection.py", line 1089, in <module>
    loop.run_until_complete(main(args))
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "defragment_sharded_collection.py", line 621, in main
    await asyncio.gather(*tasks)
  File "defragment_sharded_collection.py", line 569, in merge_chunks_on_shard
    await coll.merge_chunks(consecutive_chunks.batch)
  File "defragment_sharded_collection.py", line 137, in merge_chunks
    }, codec_options=self.cluster.client.codec_options)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymongo/database.py", line 761, in command
    codec_options, session=session, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pymongo/database.py", line 652, in _command
    client=self.__client)
  File "/usr/local/lib/python3.6/site-packages/pymongo/pool.py", line 721, in command
    exhaust_allowed=exhaust_allowed)
  File "/usr/local/lib/python3.6/site-packages/pymongo/network.py", line 163, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 167, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Failed to commit chunk merge :: caused by :: could not merge chunks, shard atlas-11qc0x-shard-0 does not contain a sequence of chunks that exactly fills the range [{ location: "US", xdr_device_id: BinData(3, 0000010095B44058BA9EC32E0FAB201F) }, { location: "US", xdr_device_id: BinData(3, 52DF6FF6CBEA442583F9942E055022A4) }), full error: {'ok': 0.0, 'errmsg': 'Failed to commit chunk merge :: caused by :: could not merge chunks, shard atlas-11qc0x-shard-0 does not contain a sequence of chunks that exactly fills the range [{ location: "US", xdr_device_id: BinData(3, 0000010095B44058BA9EC32E0FAB201F) }, { location: "US", xdr_device_id: BinData(3, 52DF6FF6CBEA442583F9942E055022A4) })', 'code': 20, 'codeName': 'IllegalOperation', 'operationTime': Timestamp(1646879043, 1), '$clusterTime': {'clusterTime': Timestamp(1646879048, 2), 'signature': {'hash': b'\xf3s#Y\x07\xc73E\x83\xe0\x19\xb4\xc5\xa2\xd1\xfdvK\x10=', 'keyId': 7072997257389277206}}}
```

In this particular case the range in question is owned by a shard-1, but the merge command complains about shard-0. In my research everything points to UUID encoding

**Comment by dryabtse** [comment]
@lindaqin determined that this resolves the issue:
```
--- a/ctools/defragment_sharded_collection.py
+++ b/ctools/defragment_sharded_collection.py
@@ -15,6 +15,8 @@ from common import Cluster, yes_no
 from copy import deepcopy
 from pymongo import errors as pymongo_errors
 from tqdm import tqdm
+from bson.codec_options import CodecOptions
+from bson.binary import UuidRepresentation

 # Ensure that the caller is using python 3
 if (sys.version_info[0] < 3):
@@ -130,10 +132,12 @@ class ShardedCollection:
     async def merge_chunks(self, consecutive_chunks):
         assert (len(consecutive_chunks) > 1)

+        codec_options = CodecOptions(uuid_representation=UuidRepresentation.STANDARD)
         await self.cluster.adminDb.command({
             'mergeChunks': self.name,
             'bounds': [consecutive_chunks[0]['min'], consecutive_chunks[-1]['max']]
-        }, codec_options=self.cluster.client.codec_options)
+        }, codec_options=codec_options)
+        #}, codec_options=self.cluster.client.codec_options)

     async def try_write_chunk_size(self, range, expected_owning_shard, size_to_write_kb):
         try:
```

**Comment by kaloianm** [comment]
Can you guys please submit a pull request?

**Comment by dryabtse** [comment]
done https://github.com/kaloianm/workscripts/pull/85
